# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

lane :IncrementBuildNumber do
    path = '../app/build.gradle'
    re = /versionCode\s+(\d+)/
    s = File.read(path)
    versionCode = s[re, 1].to_i
    s[re, 1] = (versionCode + 1).to_s
    f = File.new(path, 'w')
    f.write(s)
    f.close

end

lane :gitpush do
        git_add
        git_commit(path: "*", message: "Android version code auto incremented")
        push_to_git_remote
end

desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "bundleRelease")

    # Upload to Play Store's Internal Testing
          upload_to_play_store(
            package_name: 'com.drivevariant',
            track: "internal",
            release_status: 'draft',
            json_key: "./android/app/key.json",
            aab: "./android/app/build/outputs/bundle/release/app-release.aab"
          )
  end
end
