name: Build & Publish Android Apps
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup actions/setup-node@v1
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '>= 2.6'

      - name: Grant rights
        run: chmod +x build.gradle

      - name: Build with Gradle
        id: build
        run: ./gradlew build

      - name: Build Release AAB
        id: buildRelease
        run: ./gradlew bundleDebug

#      - name: Sign App Bundle
#        id: sign_app
#        uses: r0adkll/sign-android-release@v1
#        with:
#          releaseDirectory: android/app/build/outputs/bundle/release
#          signingKeyBase64: ${{ secrets.RELEASE_KEYSTORE_BASE64 }}
#          alias: ${{ secrets.RELEASE_KEYSTORE_ALIAS }}
#          keyStorePassword: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
#          keyPassword: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}

#      - name: Create Google store key.json
#        id: createServiceAccount
#        run: echo '${{ secrets.GOOGLE_STORE_KEY_JSON }}' > key.json

      - name: Deploy to Play Store (BETA)
        id: deploy
        uses: r0adkll/upload-google-play@v1
        with:
          packageName: com.package
          releaseFile: app/build/outputs/bundle/debug/app-debug.aab
          track: deploy


