name: Build Debug Android Apps

on: push

jobs:
  install-dependencies:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
  build-android:
    needs: install-dependencies
    runs-on: macos-latest
    defaults:
      run:
        working-directory: android
    steps:
      - name: Build Android App
        run: |
          ./gradlew assembleDebug --stacktrace
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "android/app/build/outputs/apk/debug/app-debug.apk"
      - name: File exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: echo All files exists!
      - name: Upload Debug APK
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
