name: Build & Publish Android Apps
on: push
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.x'

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install

      - name: Install Fastlane
        run: gem install fastlane

      - name: Distribute app to Beta Track 🚀
        run: |
          cd android && bundle exec fastlane beta
