name: Build Debug Android Apps
on: push
jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Build Android App
        working-directory: ./android
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "app/build/outputs/apk/debug/app-debug.apk"
      - name: File exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: echo All files exists!
      - name: Upload Debug APK
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
